#ifndef __LEPTON_REGS_H__
#define __LEPTON_REGS_H__

#define LEPTON_REGS_COMMAND_OFFSET 					(0UL << 1)
#define LEPTON_REGS_STATUS_OFFSET  					(1UL << 1)
#define LEPTON_REGS_MIN_OFFSET     					(2UL << 1)
#define LEPTON_REGS_MAX_OFFSET     					(3UL << 1)
#define LEPTON_REGS_SUM_MSB_OFFSET 					(4UL << 1)
#define LEPTON_REGS_SUM_LSB_OFFSET 					(5UL << 1)
#define LEPTON_REGS_ROW_IDX_OFFSET 					(6UL << 1)
#define LEPTON_REGS_BUFFER_OFFSET  					(8UL << 1)
#define LEPTON_REGS_ADJUSTED_BUFFER_OFFSET  		(16UL << 1)
#define LEPTON_REGS_BUFFER_SIZE	   					(80 * 60)
#define LEPTON_REGS_BUFFER_BYTELENGTH				(LEPTON_REGS_BUFFER_SIZE * 2)

#endif
