# TCL File Generated by Component Editor 16.0
# Sun Feb 05 19:28:44 CET 2017
# DO NOT MODIFY


# 
# i2c_pio "i2c_pio" v15.1
#  2017.02.05.19:28:44
# Extender GPIO over I2C PCA9673
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module i2c_pio
# 
set_module_property DESCRIPTION "Extender GPIO over I2C PCA9673"
set_module_property NAME i2c_pio
set_module_property VERSION 15.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME i2c_pio
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL i2c_pio
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file i2c_pio.vhd VHDL PATH i2c_pio.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter CLK_FREQ NATURAL 50000000
set_parameter_property CLK_FREQ DEFAULT_VALUE 50000000
set_parameter_property CLK_FREQ DISPLAY_NAME CLK_FREQ
set_parameter_property CLK_FREQ TYPE NATURAL
set_parameter_property CLK_FREQ UNITS None
set_parameter_property CLK_FREQ ALLOWED_RANGES 0:2147483647
set_parameter_property CLK_FREQ HDL_PARAMETER true
add_parameter SCL_FREQ NATURAL 1000000
set_parameter_property SCL_FREQ DEFAULT_VALUE 1000000
set_parameter_property SCL_FREQ DISPLAY_NAME SCL_FREQ
set_parameter_property SCL_FREQ TYPE NATURAL
set_parameter_property SCL_FREQ UNITS None
set_parameter_property SCL_FREQ ALLOWED_RANGES 0:2147483647
set_parameter_property SCL_FREQ HDL_PARAMETER true
add_parameter I2C_ADDR NATURAL 72
set_parameter_property I2C_ADDR DEFAULT_VALUE 72
set_parameter_property I2C_ADDR DISPLAY_NAME I2C_ADDR
set_parameter_property I2C_ADDR TYPE NATURAL
set_parameter_property I2C_ADDR UNITS None
set_parameter_property I2C_ADDR ALLOWED_RANGES 0:2147483647
set_parameter_property I2C_ADDR HDL_PARAMETER true
add_parameter PORT_LEN NATURAL 4
set_parameter_property PORT_LEN DEFAULT_VALUE 4
set_parameter_property PORT_LEN DISPLAY_NAME PORT_LEN
set_parameter_property PORT_LEN TYPE NATURAL
set_parameter_property PORT_LEN UNITS None
set_parameter_property PORT_LEN ALLOWED_RANGES 0:2147483647
set_parameter_property PORT_LEN HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input "(port_len) - (0) + 1"
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point i2c
# 
add_interface i2c conduit end
set_interface_property i2c associatedClock clock
set_interface_property i2c associatedReset ""
set_interface_property i2c ENABLED true
set_interface_property i2c EXPORT_OF ""
set_interface_property i2c PORT_NAME_MAP ""
set_interface_property i2c CMSIS_SVD_VARIABLES ""
set_interface_property i2c SVD_ADDRESS_GROUP ""

add_interface_port i2c scl scl Output 1
add_interface_port i2c sda sda Bidir 1


# 
# connection point pca9673
# 
add_interface pca9673 conduit end
set_interface_property pca9673 associatedClock clock
set_interface_property pca9673 associatedReset ""
set_interface_property pca9673 ENABLED true
set_interface_property pca9673 EXPORT_OF ""
set_interface_property pca9673 PORT_NAME_MAP ""
set_interface_property pca9673 CMSIS_SVD_VARIABLES ""
set_interface_property pca9673 SVD_ADDRESS_GROUP ""

add_interface_port pca9673 pio_int_n int_n Input 1
add_interface_port pca9673 pio_reset_n reset_n Output 1

